name: teste.Dashboard.WebApi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: "Install Angular CLI"
        run: npm install -g @angular/cli@latest

      - name: "Install dependencies"
        run: npm install

      - name: "Build"
        run: ng build --configuration=production 

  deploy:
    name: Deploy to Production
    needs: build  # Ensure build is successful before deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
